language: python
python:
    - "3.5"
    - "3.6"

# install dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pip install coveralls

# run tests
script:
    - pytest

# check for coverage
after_success:
    - coveralls