language: python
python:
    - "3.5"
    - "3.6"

# install dependencies
install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install nose

# run tests
script:
    - nosetests --with-coverage

# check for coverage
after_success:
    - coveralls