language: python
python:
    - "3.5"
    - "3.6"

# install dependencies
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install coverage

# run tests
script:
    - py.test

# check for coverage
after_success:
    - coveralls